/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IpmstscdImageTypeDetectorInformation-Type2-Message"
 * 	found in "../ISO10711.asn"
 */

#include "CongestionInfo.h"

static int
memb_congestionLength1_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 150)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_vehicleStartPosition1_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 150)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_congestionLength2_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 150)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_vehicleStartPosition2_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 150)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_CongestionInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CongestionInfo, congestionLength1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_congestionLength1_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"congestionLength1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CongestionInfo, vehicleStartPosition1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_vehicleStartPosition1_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleStartPosition1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CongestionInfo, congestionLength2),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_congestionLength2_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"congestionLength2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CongestionInfo, vehicleStartPosition2),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_vehicleStartPosition2_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vehicleStartPosition2"
		},
};
static const ber_tlv_tag_t asn_DEF_CongestionInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CongestionInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* congestionLength1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* vehicleStartPosition1 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* congestionLength2 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* vehicleStartPosition2 */
};
static asn_SEQUENCE_specifics_t asn_SPC_CongestionInfo_specs_1 = {
	sizeof(struct CongestionInfo),
	offsetof(struct CongestionInfo, _asn_ctx),
	asn_MAP_CongestionInfo_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CongestionInfo = {
	"CongestionInfo",
	"CongestionInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CongestionInfo_tags_1,
	sizeof(asn_DEF_CongestionInfo_tags_1)
		/sizeof(asn_DEF_CongestionInfo_tags_1[0]), /* 1 */
	asn_DEF_CongestionInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_CongestionInfo_tags_1)
		/sizeof(asn_DEF_CongestionInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CongestionInfo_1,
	4,	/* Elements count */
	&asn_SPC_CongestionInfo_specs_1	/* Additional specs */
};

