/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IpmstscdImageTypeDetectorInformation-Type2-Message"
 * 	found in "ISO10711.asn"
 */

#ifndef	_CongestionInfo_H_
#define	_CongestionInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CongestionInfo */
typedef struct CongestionInfo {
	long	 congestionLength1;
	long	 vehicleStartPosition1;
	long	 congestionLength2;
	long	 vehicleStartPosition2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CongestionInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CongestionInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _CongestionInfo_H_ */
#include <asn_internal.h>
