/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IpmstscdOccTypeDetectorInformation-Type2-Message"
 * 	found in "../ISO10711.asn"
 */

#ifndef	_Det_Velocity_H_
#define	_Det_Velocity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum vehicleType {
	vehicleType_bus_4	= 1,
	vehicleType_largeSizeTruck_4	= 2,
	vehicleType_smallSizeTrack_4	= 4,
	vehicleType_else_4	= 8,
	vehicleType_largeSizeVehicle_4	= 16,
	vehicleType_else_2	= 32
} e_vehicleType;

/* Det-Velocity */
typedef struct Det_Velocity {
	A_SEQUENCE_OF(struct Member {
		long	 det_nbr;
		long	 vehicleType;
		long	 velocity;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Det_Velocity_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_vehicleType_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Det_Velocity;

#ifdef __cplusplus
}
#endif

#endif	/* _Det_Velocity_H_ */
#include <asn_internal.h>
