/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IpmstscdOccTypeDetectorInformation-Type2-Message"
 * 	found in "ISO10711.asn"
 */

#ifndef	_Det_Info_H_
#define	_Det_Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Det-Info */
typedef OCTET_STRING_t	 Det_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Det_Info;
asn_struct_free_f Det_Info_free;
asn_struct_print_f Det_Info_print;
asn_constr_check_f Det_Info_constraint;
ber_type_decoder_f Det_Info_decode_ber;
der_type_encoder_f Det_Info_encode_der;
xer_type_decoder_f Det_Info_decode_xer;
xer_type_encoder_f Det_Info_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Det_Info_H_ */
#include <asn_internal.h>
