/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../Annex_A_10711_v2.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Det_AccmulatedSeq_H_
#define	_Det_AccmulatedSeq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Det_AccmulatedSeq__det_Status {
	Det_AccmulatedSeq__det_Status_normal	= 0,
	Det_AccmulatedSeq__det_Status_fault	= 1,
	Det_AccmulatedSeq__det_Status_invalid	= 2
} e_Det_AccmulatedSeq__det_Status;

/* Det-AccmulatedSeq */
typedef struct Det_AccmulatedSeq {
	long	 det_nbr;
	long	*det_Status	/* OPTIONAL */;
	long	 density;
	long	 occupancy;
	long	 detPulseErr;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Det_AccmulatedSeq_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_det_Status_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Det_AccmulatedSeq;

#ifdef __cplusplus
}
#endif

#endif	/* _Det_AccmulatedSeq_H_ */
#include <asn_internal.h>
