/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../DataPacketStructuresV3MarkRetallack.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Det_VelocitySeq_H_
#define	_Det_VelocitySeq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Det_VelocitySeq__vehicleType {
	Det_VelocitySeq__vehicleType_four_Bus	= 1,
	Det_VelocitySeq__vehicleType_four_LargeSizeTruck	= 2,
	Det_VelocitySeq__vehicleType_four_SmallSizeTrack	= 4,
	Det_VelocitySeq__vehicleType_four_else	= 8,
	Det_VelocitySeq__vehicleType_two_LargeSizeVehicle	= 16,
	Det_VelocitySeq__vehicleType_two_else	= 32
} e_Det_VelocitySeq__vehicleType;

/* Det-VelocitySeq */
typedef struct Det_VelocitySeq {
	long	 det_nbr;
	long	 vehicleType;
	long	 velocity;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Det_VelocitySeq_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_vehicleType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Det_VelocitySeq;

#ifdef __cplusplus
}
#endif

#endif	/* _Det_VelocitySeq_H_ */
#include <asn_internal.h>
