/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../DataPacketStructuresV3MarkRetallack.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DetectorControllerInformation_H_
#define	_DetectorControllerInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GeneralTimeLocationCore;

/* DetectorControllerInformation */
typedef struct DetectorControllerInformation {
	long	 detectorController_index;
	struct GeneralTimeLocationCore	*detectorController_Time_Location	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DetectorControllerInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DetectorControllerInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeneralTimeLocationCore.h"

#endif	/* _DetectorControllerInformation_H_ */
#include <asn_internal.h>
