/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IpmstscdImageTypeDetectorInformation-Type2-Message"
 * 	found in "../ISO10711.asn"
 */

#ifndef	_DirectionDensity_H_
#define	_DirectionDensity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum det_Status {
	det_Status_normal	= 0,
	det_Status_invalid	= 1
} e_det_Status;

/* DirectionDensity */
typedef struct DirectionDensity {
	A_SEQUENCE_OF(struct Member {
		long	 directionNo;
		long	*det_Status	/* OPTIONAL */;
		long	 directionDensity;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DirectionDensity_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_det_Status_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DirectionDensity;

#ifdef __cplusplus
}
#endif

#endif	/* _DirectionDensity_H_ */
#include <asn_internal.h>
