/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../DataPacketStructuresV3MarkRetallack.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_GeneralTimeLocationCore_H_
#define	_GeneralTimeLocationCore_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Time.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GeneralTimeLocationCore */
typedef struct GeneralTimeLocationCore {
	Time_t	 currentTime;
	long	*locationLongitude	/* OPTIONAL */;
	long	*locationLatitude	/* OPTIONAL */;
	long	*locationElevation	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GeneralTimeLocationCore_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GeneralTimeLocationCore;

#ifdef __cplusplus
}
#endif

#endif	/* _GeneralTimeLocationCore_H_ */
#include <asn_internal.h>
