/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../DataPacketStructuresV3MarkRetallack.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IpmstscdOccTypeDetectorInformationType2_H_
#define	_IpmstscdOccTypeDetectorInformationType2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Det_AccmulatedSeq;
struct Det_SerialInfoSeq;
struct Det_VelocitySeq;

/* IpmstscdOccTypeDetectorInformationType2 */
typedef struct IpmstscdOccTypeDetectorInformationType2 {
	struct IpmstscdOccTypeDetectorInformationType2__det_Accmulated {
		A_SEQUENCE_OF(struct Det_AccmulatedSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} det_Accmulated;
	struct IpmstscdOccTypeDetectorInformationType2__det_SerialInfo {
		A_SEQUENCE_OF(struct Det_SerialInfoSeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} det_SerialInfo;
	struct IpmstscdOccTypeDetectorInformationType2__det_Velocity {
		A_SEQUENCE_OF(struct Det_VelocitySeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} det_Velocity;
	OCTET_STRING_t	 det_Info;
	OCTET_STRING_t	*iDetStatus	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpmstscdOccTypeDetectorInformationType2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IpmstscdOccTypeDetectorInformationType2;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Det-AccmulatedSeq.h"
#include "Det-SerialInfoSeq.h"
#include "Det-VelocitySeq.h"

#endif	/* _IpmstscdOccTypeDetectorInformationType2_H_ */
#include <asn_internal.h>
