/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IpmstscdIDTypeDetectorInformation-Type2-Message"
 * 	found in "../ISO10711.asn"
 */

#ifndef	_IpmstscdIDTypeDetectorInformation_H_
#define	_IpmstscdIDTypeDetectorInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <NativeReal.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum idDeviceType {
	idDeviceType_infra_Red	= 0,
	idDeviceType_radio_Frequency	= 1,
	idDeviceType_vdss	= 2,
	idDeviceType_magnetics	= 3,
	idDeviceType_barCodeScanner	= 4,
	idDeviceType_tagScanner	= 5,
	idDeviceType_other	= 6
} e_idDeviceType;
typedef enum idErrorState {
	idErrorState_rseFail	= 1,
	idErrorState_rse_ConnectionFail	= 2,
	idErrorState_wirelessFail	= 3,
	idErrorState_unstableUtility	= 4,
	idErrorState_managementNeeded	= 5
} e_idErrorState;

/* IpmstscdIDTypeDetectorInformation */
typedef struct IpmstscdIDTypeDetectorInformation {
	long	 idSequenceNumber;
	long	*idDeviceType	/* OPTIONAL */;
	OCTET_STRING_t	 idVehicleIdentity;
	long	*idVehicleType	/* OPTIONAL */;
	long	*idVehicleUse	/* OPTIONAL */;
	long	*idDetectionLane	/* OPTIONAL */;
	long	*idDetectionLaneMedian	/* OPTIONAL */;
	double	*idDetectionSpeed	/* OPTIONAL */;
	long	*idOccupancy	/* OPTIONAL */;
	long	*idErrorState	/* OPTIONAL */;
	OCTET_STRING_t	*idTagInfo	/* OPTIONAL */;
	OCTET_STRING_t	*idUserData	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpmstscdIDTypeDetectorInformation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_idDeviceType_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_idErrorState_18;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IpmstscdIDTypeDetectorInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _IpmstscdIDTypeDetectorInformation_H_ */
#include <asn_internal.h>
