/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IpmstscdLoopTypeDetectorInformation-Type2-Message"
 * 	found in "../ISO10711.asn"
 */

#ifndef	_IpmstscdOccNoccHistory_H_
#define	_IpmstscdOccNoccHistory_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IpmstscdOccNoccHistory */
typedef struct IpmstscdOccNoccHistory {
	long	 occupancyTimes;
	long	 nonOccupancyTimes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpmstscdOccNoccHistory_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IpmstscdOccNoccHistory;

#ifdef __cplusplus
}
#endif

#endif	/* _IpmstscdOccNoccHistory_H_ */
#include <asn_internal.h>
