/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../Annex_A_10711_v2.0.asn"
 * 	`asn1c -fcompound-names`
 */

#include "IPMSTSCDData.h"

static int
memb_detectorController_index_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_ipmstscdDetData_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_IpmstscdDetDataSeq,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ipmstscdDetData_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ipmstscdDetData_specs_4 = {
	sizeof(struct IPMSTSCDData__ipmstscdDetData),
	offsetof(struct IPMSTSCDData__ipmstscdDetData, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ipmstscdDetData_4 = {
	"ipmstscdDetData",
	"ipmstscdDetData",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ipmstscdDetData_tags_4,
	sizeof(asn_DEF_ipmstscdDetData_tags_4)
		/sizeof(asn_DEF_ipmstscdDetData_tags_4[0]) - 1, /* 1 */
	asn_DEF_ipmstscdDetData_tags_4,	/* Same as above */
	sizeof(asn_DEF_ipmstscdDetData_tags_4)
		/sizeof(asn_DEF_ipmstscdDetData_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ipmstscdDetData_4,
	1,	/* Single element */
	&asn_SPC_ipmstscdDetData_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_IPMSTSCDData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IPMSTSCDData, detectorController_index),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_detectorController_index_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"detectorController-index"
		},
	{ ATF_POINTER, 2, offsetof(struct IPMSTSCDData, detectorController_Time_Location),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralTimeLocationCore,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"detectorController-Time-Location"
		},
	{ ATF_POINTER, 1, offsetof(struct IPMSTSCDData, ipmstscdDetData),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_ipmstscdDetData_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ipmstscdDetData"
		},
};
static const ber_tlv_tag_t asn_DEF_IPMSTSCDData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IPMSTSCDData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* detectorController-index */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* detectorController-Time-Location */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ipmstscdDetData */
};
static asn_SEQUENCE_specifics_t asn_SPC_IPMSTSCDData_specs_1 = {
	sizeof(struct IPMSTSCDData),
	offsetof(struct IPMSTSCDData, _asn_ctx),
	asn_MAP_IPMSTSCDData_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_IPMSTSCDData = {
	"IPMSTSCDData",
	"IPMSTSCDData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_IPMSTSCDData_tags_1,
	sizeof(asn_DEF_IPMSTSCDData_tags_1)
		/sizeof(asn_DEF_IPMSTSCDData_tags_1[0]), /* 1 */
	asn_DEF_IPMSTSCDData_tags_1,	/* Same as above */
	sizeof(asn_DEF_IPMSTSCDData_tags_1)
		/sizeof(asn_DEF_IPMSTSCDData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_IPMSTSCDData_1,
	3,	/* Elements count */
	&asn_SPC_IPMSTSCDData_specs_1	/* Additional specs */
};

