/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../DataPacketStructuresV3MarkRetallack.asn"
 * 	`asn1c -fcompound-names`
 */

#include "IpmstscdOccTypeDetectorInformation.h"

static int
occupancyErrorState_11_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
occupancyErrorState_11_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
occupancyErrorState_11_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	occupancyErrorState_11_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
occupancyErrorState_11_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	occupancyErrorState_11_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
occupancyErrorState_11_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	occupancyErrorState_11_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
occupancyErrorState_11_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	occupancyErrorState_11_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
occupancyErrorState_11_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	occupancyErrorState_11_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
occupancyErrorState_11_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	occupancyErrorState_11_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
memb_occupancyStateDuration_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_occupancyPreviousStateDuration_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_targetType_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_occNoccHistory_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_IpmstscdOccNoccHistory,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_occNoccHistory_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_occNoccHistory_specs_9 = {
	sizeof(struct IpmstscdOccTypeDetectorInformation__occNoccHistory),
	offsetof(struct IpmstscdOccTypeDetectorInformation__occNoccHistory, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_occNoccHistory_9 = {
	"occNoccHistory",
	"occNoccHistory",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_occNoccHistory_tags_9,
	sizeof(asn_DEF_occNoccHistory_tags_9)
		/sizeof(asn_DEF_occNoccHistory_tags_9[0]) - 1, /* 1 */
	asn_DEF_occNoccHistory_tags_9,	/* Same as above */
	sizeof(asn_DEF_occNoccHistory_tags_9)
		/sizeof(asn_DEF_occNoccHistory_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_occNoccHistory_9,
	1,	/* Single element */
	&asn_SPC_occNoccHistory_specs_9	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_occupancyErrorState_value2enum_11[] = {
	{ 1,	11,	"openCircuit" },
	{ 2,	12,	"shortCircuit" },
	{ 3,	14,	"occupancyError" },
	{ 4,	17,	"nonoccupancyError" },
	{ 5,	11,	"volumeError" },
	{ 6,	16,	"parameterInvalid" },
	{ 7,	16,	"managementNeeded" }
};
static const unsigned int asn_MAP_occupancyErrorState_enum2value_11[] = {
	6,	/* managementNeeded(7) */
	3,	/* nonoccupancyError(4) */
	2,	/* occupancyError(3) */
	0,	/* openCircuit(1) */
	5,	/* parameterInvalid(6) */
	1,	/* shortCircuit(2) */
	4	/* volumeError(5) */
};
static const asn_INTEGER_specifics_t asn_SPC_occupancyErrorState_specs_11 = {
	asn_MAP_occupancyErrorState_value2enum_11,	/* "tag" => N; sorted by tag */
	asn_MAP_occupancyErrorState_enum2value_11,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_occupancyErrorState_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_occupancyErrorState_11 = {
	"occupancyErrorState",
	"occupancyErrorState",
	occupancyErrorState_11_free,
	occupancyErrorState_11_print,
	occupancyErrorState_11_constraint,
	occupancyErrorState_11_decode_ber,
	occupancyErrorState_11_encode_der,
	occupancyErrorState_11_decode_xer,
	occupancyErrorState_11_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_occupancyErrorState_tags_11,
	sizeof(asn_DEF_occupancyErrorState_tags_11)
		/sizeof(asn_DEF_occupancyErrorState_tags_11[0]) - 1, /* 1 */
	asn_DEF_occupancyErrorState_tags_11,	/* Same as above */
	sizeof(asn_DEF_occupancyErrorState_tags_11)
		/sizeof(asn_DEF_occupancyErrorState_tags_11[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_occupancyErrorState_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_IpmstscdOccTypeDetectorInformation_1[] = {
	{ ATF_POINTER, 1, offsetof(struct IpmstscdOccTypeDetectorInformation, occupancyDataDuration),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occupancyDataDuration"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpmstscdOccTypeDetectorInformation, occupancyState),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occupancyState"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpmstscdOccTypeDetectorInformation, occupancyStateDuration),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_occupancyStateDuration_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occupancyStateDuration"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpmstscdOccTypeDetectorInformation, occupancyPreviousStateDuration),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_occupancyPreviousStateDuration_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occupancyPreviousStateDuration"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpmstscdOccTypeDetectorInformation, occupancyRate),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occupancyRate"
		},
	{ ATF_POINTER, 1, offsetof(struct IpmstscdOccTypeDetectorInformation, occupancySpeed),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occupancySpeed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpmstscdOccTypeDetectorInformation, occupancyVolume),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occupancyVolume"
		},
	{ ATF_POINTER, 5, offsetof(struct IpmstscdOccTypeDetectorInformation, occNoccHistory),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_occNoccHistory_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occNoccHistory"
		},
	{ ATF_POINTER, 4, offsetof(struct IpmstscdOccTypeDetectorInformation, occupancyErrorState),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_occupancyErrorState_11,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"occupancyErrorState"
		},
	{ ATF_POINTER, 3, offsetof(struct IpmstscdOccTypeDetectorInformation, userData),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"userData"
		},
	{ ATF_POINTER, 2, offsetof(struct IpmstscdOccTypeDetectorInformation, targetType),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_targetType_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"targetType"
		},
	{ ATF_POINTER, 1, offsetof(struct IpmstscdOccTypeDetectorInformation, directionDiscrimination),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"directionDiscrimination"
		},
};
static const ber_tlv_tag_t asn_DEF_IpmstscdOccTypeDetectorInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IpmstscdOccTypeDetectorInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* occupancyDataDuration */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* occupancyState */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* occupancyStateDuration */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* occupancyPreviousStateDuration */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* occupancyRate */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* occupancySpeed */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* occupancyVolume */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* occNoccHistory */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* occupancyErrorState */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* userData */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* targetType */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* directionDiscrimination */
};
static asn_SEQUENCE_specifics_t asn_SPC_IpmstscdOccTypeDetectorInformation_specs_1 = {
	sizeof(struct IpmstscdOccTypeDetectorInformation),
	offsetof(struct IpmstscdOccTypeDetectorInformation, _asn_ctx),
	asn_MAP_IpmstscdOccTypeDetectorInformation_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_IpmstscdOccTypeDetectorInformation = {
	"IpmstscdOccTypeDetectorInformation",
	"IpmstscdOccTypeDetectorInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_IpmstscdOccTypeDetectorInformation_tags_1,
	sizeof(asn_DEF_IpmstscdOccTypeDetectorInformation_tags_1)
		/sizeof(asn_DEF_IpmstscdOccTypeDetectorInformation_tags_1[0]), /* 1 */
	asn_DEF_IpmstscdOccTypeDetectorInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_IpmstscdOccTypeDetectorInformation_tags_1)
		/sizeof(asn_DEF_IpmstscdOccTypeDetectorInformation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_IpmstscdOccTypeDetectorInformation_1,
	12,	/* Elements count */
	&asn_SPC_IpmstscdOccTypeDetectorInformation_specs_1	/* Additional specs */
};

