/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../Annex_A_10711_v2.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IpmstscdImageTypeDetectorInformation_H_
#define	_IpmstscdImageTypeDetectorInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeReal.h>
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IpmstscdImageTypeDetectorInformation__imgErrorState {
	IpmstscdImageTypeDetectorInformation__imgErrorState_deviceFail	= 1,
	IpmstscdImageTypeDetectorInformation__imgErrorState_unstableUtility	= 2,
	IpmstscdImageTypeDetectorInformation__imgErrorState_connectionFail	= 3,
	IpmstscdImageTypeDetectorInformation__imgErrorState_imageProcessingFail	= 4,
	IpmstscdImageTypeDetectorInformation__imgErrorState_parameterInvalid	= 5,
	IpmstscdImageTypeDetectorInformation__imgErrorState_volumeError	= 6,
	IpmstscdImageTypeDetectorInformation__imgErrorState_managementNeeded	= 7
	/*
	 * Enumeration is extensible
	 */
} e_IpmstscdImageTypeDetectorInformation__imgErrorState;

/* Forward declarations */
struct IpmstscdOccNoccHistory;

/* IpmstscdImageTypeDetectorInformation */
typedef struct IpmstscdImageTypeDetectorInformation {
	long	*imgDataDuration	/* OPTIONAL */;
	long	*imgQueueLength	/* OPTIONAL */;
	double	*imgOccupancyRate	/* OPTIONAL */;
	double	*imgSpeed	/* OPTIONAL */;
	long	 imgVolume;
	struct IpmstscdOccNoccHistory	*imgOccNoccHistory	/* OPTIONAL */;
	long	*imgErrorState	/* OPTIONAL */;
	OCTET_STRING_t	*imgUserData	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpmstscdImageTypeDetectorInformation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_imgErrorState_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IpmstscdImageTypeDetectorInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IpmstscdOccNoccHistory.h"

#endif	/* _IpmstscdImageTypeDetectorInformation_H_ */
#include <asn_internal.h>
