/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../DataPacketStructuresV3MarkRetallack.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IpmstscdDetDataSeq_H_
#define	_IpmstscdDetDataSeq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include "IpmstscdOccTypeDetectorInformation.h"
#include "IpmstscdImageTypeDetectorInformation.h"
#include "IpmstscdIDTypeDetectorInformation.h"
#include "IpmstscdOccTypeDetectorInformationType2.h"
#include "IpmstscdImageTypeDetectorInformationType2.h"
#include "IpmstscdIDTypeDetectorInformationType2.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IpmstscdDetDataSeq__ipmstscdDetType {
	IpmstscdDetDataSeq__ipmstscdDetType_occupancyTypeDetector	= 0,
	IpmstscdDetDataSeq__ipmstscdDetType_imageTypeDetector	= 1,
	IpmstscdDetDataSeq__ipmstscdDetType_idBaseTypeDetector	= 2
	/*
	 * Enumeration is extensible
	 */
} e_IpmstscdDetDataSeq__ipmstscdDetType;
typedef enum IpmstscdDetDataSeq__ipmstscdDetInformation_PR {
	IpmstscdDetDataSeq__ipmstscdDetInformation_PR_NOTHING,	/* No components present */
	IpmstscdDetDataSeq__ipmstscdDetInformation_PR_occupancyTypeDetInf,
	IpmstscdDetDataSeq__ipmstscdDetInformation_PR_imageTypeDetInf,
	IpmstscdDetDataSeq__ipmstscdDetInformation_PR_idTypeDetInfo,
	IpmstscdDetDataSeq__ipmstscdDetInformation_PR_occTypeDetInftype2,
	IpmstscdDetDataSeq__ipmstscdDetInformation_PR_imageTypeDetInftype2,
	IpmstscdDetDataSeq__ipmstscdDetInformation_PR_idTypeDetInfotype2,
	/* Extensions may appear below */
	
} IpmstscdDetDataSeq__ipmstscdDetInformation_PR;

/* Forward declarations */
struct GeneralTimeLocationCore;

/* IpmstscdDetDataSeq */
typedef struct IpmstscdDetDataSeq {
	long	 ipmstscdDetID;
	long	 ipmstscdDetType;
	struct IpmstscdDetDataSeq__ipmstscdDetInformation {
		IpmstscdDetDataSeq__ipmstscdDetInformation_PR present;
		union IpmstscdDetDataSeq__ipmstscdDetInformation_u {
			IpmstscdOccTypeDetectorInformation_t	 occupancyTypeDetInf;
			IpmstscdImageTypeDetectorInformation_t	 imageTypeDetInf;
			IpmstscdIDTypeDetectorInformation_t	 idTypeDetInfo;
			IpmstscdOccTypeDetectorInformationType2_t	 occTypeDetInftype2;
			IpmstscdImageTypeDetectorInformationType2_t	 imageTypeDetInftype2;
			IpmstscdIDTypeDetectorInformationType2_t	 idTypeDetInfotype2;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ipmstscdDetInformation;
	struct GeneralTimeLocationCore	*detector_Time_Location	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpmstscdDetDataSeq_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ipmstscdDetType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IpmstscdDetDataSeq;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeneralTimeLocationCore.h"

#endif	/* _IpmstscdDetDataSeq_H_ */
#include <asn_internal.h>
