/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../DataPacketStructuresV3MarkRetallack.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IpmstscdOccTypeDetectorInformation_H_
#define	_IpmstscdOccTypeDetectorInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <NativeReal.h>
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IpmstscdOccTypeDetectorInformation__occupancyErrorState {
	IpmstscdOccTypeDetectorInformation__occupancyErrorState_openCircuit	= 1,
	IpmstscdOccTypeDetectorInformation__occupancyErrorState_shortCircuit	= 2,
	IpmstscdOccTypeDetectorInformation__occupancyErrorState_occupancyError	= 3,
	IpmstscdOccTypeDetectorInformation__occupancyErrorState_nonoccupancyError	= 4,
	IpmstscdOccTypeDetectorInformation__occupancyErrorState_volumeError	= 5,
	IpmstscdOccTypeDetectorInformation__occupancyErrorState_parameterInvalid	= 6,
	IpmstscdOccTypeDetectorInformation__occupancyErrorState_managementNeeded	= 7
} e_IpmstscdOccTypeDetectorInformation__occupancyErrorState;

/* Forward declarations */
struct IpmstscdOccNoccHistory;

/* IpmstscdOccTypeDetectorInformation */
typedef struct IpmstscdOccTypeDetectorInformation {
	long	*occupancyDataDuration	/* OPTIONAL */;
	BOOLEAN_t	 occupancyState;
	long	 occupancyStateDuration;
	long	 occupancyPreviousStateDuration;
	double	 occupancyRate;
	double	*occupancySpeed	/* OPTIONAL */;
	long	 occupancyVolume;
	struct IpmstscdOccTypeDetectorInformation__occNoccHistory {
		A_SEQUENCE_OF(struct IpmstscdOccNoccHistory) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *occNoccHistory;
	long	*occupancyErrorState	/* OPTIONAL */;
	OCTET_STRING_t	*userData	/* OPTIONAL */;
	long	*targetType	/* OPTIONAL */;
	BOOLEAN_t	*directionDiscrimination	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpmstscdOccTypeDetectorInformation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_occupancyErrorState_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IpmstscdOccTypeDetectorInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IpmstscdOccNoccHistory.h"

#endif	/* _IpmstscdOccTypeDetectorInformation_H_ */
#include <asn_internal.h>
