/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IpmstscdIDTypeDetectorInformation-Type2-Message"
 * 	found in "../ISO10711.asn"
 */

#include "IpmstscdIDTypeDetectorInformation.h"

static int
idDeviceType_3_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
idDeviceType_3_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
idDeviceType_3_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	idDeviceType_3_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
idDeviceType_3_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	idDeviceType_3_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
idDeviceType_3_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	idDeviceType_3_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
idDeviceType_3_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	idDeviceType_3_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
idDeviceType_3_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	idDeviceType_3_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
idDeviceType_3_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	idDeviceType_3_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
idErrorState_19_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
idErrorState_19_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
idErrorState_19_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	idErrorState_19_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
idErrorState_19_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	idErrorState_19_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
idErrorState_19_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	idErrorState_19_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
idErrorState_19_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	idErrorState_19_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
idErrorState_19_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	idErrorState_19_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
idErrorState_19_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	idErrorState_19_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
memb_idSequenceNumber_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_idDetectionLane_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_idDetectionLaneMedian_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static const asn_INTEGER_enum_map_t asn_MAP_idDeviceType_value2enum_3[] = {
	{ 0,	9,	"infra-Red" },
	{ 1,	15,	"radio-Frequency" },
	{ 2,	4,	"vdss" },
	{ 3,	9,	"magnetics" },
	{ 4,	14,	"barCodeScanner" },
	{ 5,	10,	"tagScanner" },
	{ 6,	5,	"other" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_idDeviceType_enum2value_3[] = {
	4,	/* barCodeScanner(4) */
	0,	/* infra-Red(0) */
	3,	/* magnetics(3) */
	6,	/* other(6) */
	1,	/* radio-Frequency(1) */
	5,	/* tagScanner(5) */
	2	/* vdss(2) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_idDeviceType_specs_3 = {
	asn_MAP_idDeviceType_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_idDeviceType_enum2value_3,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	8,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_idDeviceType_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_idDeviceType_3 = {
	"idDeviceType",
	"idDeviceType",
	idDeviceType_3_free,
	idDeviceType_3_print,
	idDeviceType_3_constraint,
	idDeviceType_3_decode_ber,
	idDeviceType_3_encode_der,
	idDeviceType_3_decode_xer,
	idDeviceType_3_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_idDeviceType_tags_3,
	sizeof(asn_DEF_idDeviceType_tags_3)
		/sizeof(asn_DEF_idDeviceType_tags_3[0]) - 1, /* 1 */
	asn_DEF_idDeviceType_tags_3,	/* Same as above */
	sizeof(asn_DEF_idDeviceType_tags_3)
		/sizeof(asn_DEF_idDeviceType_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_idDeviceType_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_idErrorState_value2enum_19[] = {
	{ 1,	7,	"rseFail" },
	{ 2,	18,	"rse-ConnectionFail" },
	{ 3,	12,	"wirelessFail" },
	{ 4,	15,	"unstableUtility" },
	{ 5,	16,	"managementNeeded" }
};
static const unsigned int asn_MAP_idErrorState_enum2value_19[] = {
	4,	/* managementNeeded(5) */
	1,	/* rse-ConnectionFail(2) */
	0,	/* rseFail(1) */
	3,	/* unstableUtility(4) */
	2	/* wirelessFail(3) */
};
static const asn_INTEGER_specifics_t asn_SPC_idErrorState_specs_19 = {
	asn_MAP_idErrorState_value2enum_19,	/* "tag" => N; sorted by tag */
	asn_MAP_idErrorState_enum2value_19,	/* N => "tag"; sorted by N */
	5,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_idErrorState_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_idErrorState_19 = {
	"idErrorState",
	"idErrorState",
	idErrorState_19_free,
	idErrorState_19_print,
	idErrorState_19_constraint,
	idErrorState_19_decode_ber,
	idErrorState_19_encode_der,
	idErrorState_19_decode_xer,
	idErrorState_19_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_idErrorState_tags_19,
	sizeof(asn_DEF_idErrorState_tags_19)
		/sizeof(asn_DEF_idErrorState_tags_19[0]) - 1, /* 1 */
	asn_DEF_idErrorState_tags_19,	/* Same as above */
	sizeof(asn_DEF_idErrorState_tags_19)
		/sizeof(asn_DEF_idErrorState_tags_19[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_idErrorState_specs_19	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_IpmstscdIDTypeDetectorInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IpmstscdIDTypeDetectorInformation, idSequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_idSequenceNumber_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idSequenceNumber"
		},
	{ ATF_POINTER, 1, offsetof(struct IpmstscdIDTypeDetectorInformation, idDeviceType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_idDeviceType_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idDeviceType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpmstscdIDTypeDetectorInformation, idVehicleIdentity),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idVehicleIdentity"
		},
	{ ATF_POINTER, 9, offsetof(struct IpmstscdIDTypeDetectorInformation, idVehicleType),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idVehicleType"
		},
	{ ATF_POINTER, 8, offsetof(struct IpmstscdIDTypeDetectorInformation, idVehicleUse),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idVehicleUse"
		},
	{ ATF_POINTER, 7, offsetof(struct IpmstscdIDTypeDetectorInformation, idDetectionLane),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_idDetectionLane_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idDetectionLane"
		},
	{ ATF_POINTER, 6, offsetof(struct IpmstscdIDTypeDetectorInformation, idDetectionLaneMedian),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_idDetectionLaneMedian_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idDetectionLaneMedian"
		},
	{ ATF_POINTER, 5, offsetof(struct IpmstscdIDTypeDetectorInformation, idDetectionSpeed),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idDetectionSpeed"
		},
	{ ATF_POINTER, 4, offsetof(struct IpmstscdIDTypeDetectorInformation, idOccupancy),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idOccupancy"
		},
	{ ATF_POINTER, 3, offsetof(struct IpmstscdIDTypeDetectorInformation, idErrorState),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_idErrorState_19,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idErrorState"
		},
	{ ATF_POINTER, 2, offsetof(struct IpmstscdIDTypeDetectorInformation, idTagInfo),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idTagInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct IpmstscdIDTypeDetectorInformation, idUserData),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idUserData"
		},
};
static const ber_tlv_tag_t asn_DEF_IpmstscdIDTypeDetectorInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IpmstscdIDTypeDetectorInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* idSequenceNumber */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* idDeviceType */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* idVehicleIdentity */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* idVehicleType */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* idVehicleUse */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* idDetectionLane */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* idDetectionLaneMedian */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* idDetectionSpeed */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* idOccupancy */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* idErrorState */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* idTagInfo */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* idUserData */
};
static asn_SEQUENCE_specifics_t asn_SPC_IpmstscdIDTypeDetectorInformation_specs_1 = {
	sizeof(struct IpmstscdIDTypeDetectorInformation),
	offsetof(struct IpmstscdIDTypeDetectorInformation, _asn_ctx),
	asn_MAP_IpmstscdIDTypeDetectorInformation_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_IpmstscdIDTypeDetectorInformation = {
	"IpmstscdIDTypeDetectorInformation",
	"IpmstscdIDTypeDetectorInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_IpmstscdIDTypeDetectorInformation_tags_1,
	sizeof(asn_DEF_IpmstscdIDTypeDetectorInformation_tags_1)
		/sizeof(asn_DEF_IpmstscdIDTypeDetectorInformation_tags_1[0]), /* 1 */
	asn_DEF_IpmstscdIDTypeDetectorInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_IpmstscdIDTypeDetectorInformation_tags_1)
		/sizeof(asn_DEF_IpmstscdIDTypeDetectorInformation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_IpmstscdIDTypeDetectorInformation_1,
	12,	/* Elements count */
	&asn_SPC_IpmstscdIDTypeDetectorInformation_specs_1	/* Additional specs */
};

