/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../DataPacketStructuresV3MarkRetallack.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IpmstscdIDTypeDetectorInformation_H_
#define	_IpmstscdIDTypeDetectorInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <NativeReal.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IpmstscdIDTypeDetectorInformation__deviceType {
	IpmstscdIDTypeDetectorInformation__deviceType_infra_Red	= 0,
	IpmstscdIDTypeDetectorInformation__deviceType_radio_Frequency	= 1,
	IpmstscdIDTypeDetectorInformation__deviceType_vDSs	= 2,
	IpmstscdIDTypeDetectorInformation__deviceType_magnetics	= 3,
	IpmstscdIDTypeDetectorInformation__deviceType_barCodeScanner	= 4,
	IpmstscdIDTypeDetectorInformation__deviceType_tagScanner	= 5,
	IpmstscdIDTypeDetectorInformation__deviceType_other	= 6
	/*
	 * Enumeration is extensible
	 */
} e_IpmstscdIDTypeDetectorInformation__deviceType;
typedef enum IpmstscdIDTypeDetectorInformation__errorState {
	IpmstscdIDTypeDetectorInformation__errorState_rSEFail	= 1,
	IpmstscdIDTypeDetectorInformation__errorState_rSE_ConnectionFail	= 2,
	IpmstscdIDTypeDetectorInformation__errorState_wirelessFail	= 3,
	IpmstscdIDTypeDetectorInformation__errorState_unstableUtility	= 4,
	IpmstscdIDTypeDetectorInformation__errorState_managementNeeded	= 5
} e_IpmstscdIDTypeDetectorInformation__errorState;

/* IpmstscdIDTypeDetectorInformation */
typedef struct IpmstscdIDTypeDetectorInformation {
	long	 sequenceNumber;
	long	*deviceType	/* OPTIONAL */;
	OCTET_STRING_t	 vehicleIdentity;
	long	*vehicleType	/* OPTIONAL */;
	long	*vehicleUse	/* OPTIONAL */;
	long	*detectionLane	/* OPTIONAL */;
	long	*detectionLaneMedian	/* OPTIONAL */;
	double	*detectionSpeed	/* OPTIONAL */;
	long	*occupancy	/* OPTIONAL */;
	long	*errorState	/* OPTIONAL */;
	OCTET_STRING_t	*idTagInfo	/* OPTIONAL */;
	OCTET_STRING_t	*idUserData	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpmstscdIDTypeDetectorInformation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_deviceType_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_errorState_19;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IpmstscdIDTypeDetectorInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _IpmstscdIDTypeDetectorInformation_H_ */
#include <asn_internal.h>
