/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "ISO10711.asn"
 */

#include "IPMSTSCD-Data.h"

static int
ipmstscdDetType_7_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
ipmstscdDetType_7_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
ipmstscdDetType_7_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	ipmstscdDetType_7_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
ipmstscdDetType_7_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	ipmstscdDetType_7_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
ipmstscdDetType_7_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	ipmstscdDetType_7_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
ipmstscdDetType_7_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ipmstscdDetType_7_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
ipmstscdDetType_7_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	ipmstscdDetType_7_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
ipmstscdDetType_7_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	ipmstscdDetType_7_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static int
memb_ipmstscdDetID_constraint_5(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_detectorController_index_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static const asn_INTEGER_enum_map_t asn_MAP_ipmstscdDetType_value2enum_7[] = {
	{ 0,	16,	"loopTypeDetector" },
	{ 1,	17,	"imageTypeDetector" },
	{ 2,	18,	"idBaseTypeDetector" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ipmstscdDetType_enum2value_7[] = {
	2,	/* idBaseTypeDetector(2) */
	1,	/* imageTypeDetector(1) */
	0	/* loopTypeDetector(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_ipmstscdDetType_specs_7 = {
	asn_MAP_ipmstscdDetType_value2enum_7,	/* "tag" => N; sorted by tag */
	asn_MAP_ipmstscdDetType_enum2value_7,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	4,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ipmstscdDetType_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ipmstscdDetType_7 = {
	"ipmstscdDetType",
	"ipmstscdDetType",
	ipmstscdDetType_7_free,
	ipmstscdDetType_7_print,
	ipmstscdDetType_7_constraint,
	ipmstscdDetType_7_decode_ber,
	ipmstscdDetType_7_encode_der,
	ipmstscdDetType_7_decode_xer,
	ipmstscdDetType_7_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ipmstscdDetType_tags_7,
	sizeof(asn_DEF_ipmstscdDetType_tags_7)
		/sizeof(asn_DEF_ipmstscdDetType_tags_7[0]) - 1, /* 1 */
	asn_DEF_ipmstscdDetType_tags_7,	/* Same as above */
	sizeof(asn_DEF_ipmstscdDetType_tags_7)
		/sizeof(asn_DEF_ipmstscdDetType_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ipmstscdDetType_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ipmstscdDetInformation_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ipmstscdDetInformation, choice.loopTypeDetInf),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IpmstscdLoopTypeDetectorInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"loopTypeDetInf"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ipmstscdDetInformation, choice.imageTypeDetInf),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IpmstscdImageTypeDetectorInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imageTypeDetInf"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ipmstscdDetInformation, choice.idTypeDetInfo),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IpmstscdIDTypeDetectorInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"idTypeDetInfo"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ipmstscdDetInformation_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* loopTypeDetInf */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* imageTypeDetInf */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* idTypeDetInfo */
};
static asn_CHOICE_specifics_t asn_SPC_ipmstscdDetInformation_specs_12 = {
	sizeof(struct ipmstscdDetInformation),
	offsetof(struct ipmstscdDetInformation, _asn_ctx),
	offsetof(struct ipmstscdDetInformation, present),
	sizeof(((struct ipmstscdDetInformation *)0)->present),
	asn_MAP_ipmstscdDetInformation_tag2el_12,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ipmstscdDetInformation_12 = {
	"ipmstscdDetInformation",
	"ipmstscdDetInformation",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ipmstscdDetInformation_12,
	3,	/* Elements count */
	&asn_SPC_ipmstscdDetInformation_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Member, ipmstscdDetID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_ipmstscdDetID_constraint_5,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ipmstscdDetID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Member, ipmstscdDetType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ipmstscdDetType_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ipmstscdDetType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Member, ipmstscdDetInformation),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ipmstscdDetInformation_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ipmstscdDetInformation"
		},
	{ ATF_POINTER, 1, offsetof(struct Member, detector_time_location),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralTimeLocationCore,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"detector-time-location"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ipmstscdDetID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ipmstscdDetType */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ipmstscdDetInformation */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* detector-time-location */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_5 = {
	sizeof(struct Member),
	offsetof(struct Member, _asn_ctx),
	asn_MAP_Member_tag2el_5,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_5 = {
	"SEQUENCE",
	"SEQUENCE",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Member_tags_5,
	sizeof(asn_DEF_Member_tags_5)
		/sizeof(asn_DEF_Member_tags_5[0]), /* 1 */
	asn_DEF_Member_tags_5,	/* Same as above */
	sizeof(asn_DEF_Member_tags_5)
		/sizeof(asn_DEF_Member_tags_5[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Member_5,
	4,	/* Elements count */
	&asn_SPC_Member_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ipmstscdDetData_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ipmstscdDetData_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ipmstscdDetData_specs_4 = {
	sizeof(struct ipmstscdDetData),
	offsetof(struct ipmstscdDetData, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ipmstscdDetData_4 = {
	"ipmstscdDetData",
	"ipmstscdDetData",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ipmstscdDetData_tags_4,
	sizeof(asn_DEF_ipmstscdDetData_tags_4)
		/sizeof(asn_DEF_ipmstscdDetData_tags_4[0]) - 1, /* 1 */
	asn_DEF_ipmstscdDetData_tags_4,	/* Same as above */
	sizeof(asn_DEF_ipmstscdDetData_tags_4)
		/sizeof(asn_DEF_ipmstscdDetData_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_ipmstscdDetData_4,
	1,	/* Single element */
	&asn_SPC_ipmstscdDetData_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_IPMSTSCD_Data_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IPMSTSCD_Data, detectorController_index),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_detectorController_index_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"detectorController-index"
		},
	{ ATF_POINTER, 2, offsetof(struct IPMSTSCD_Data, detectorController_Time_Location),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralTimeLocationCore,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"detectorController-Time-Location"
		},
	{ ATF_POINTER, 1, offsetof(struct IPMSTSCD_Data, ipmstscdDetData),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_ipmstscdDetData_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ipmstscdDetData"
		},
};
static const ber_tlv_tag_t asn_DEF_IPMSTSCD_Data_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IPMSTSCD_Data_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* detectorController-index */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* detectorController-Time-Location */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ipmstscdDetData */
};
static asn_SEQUENCE_specifics_t asn_SPC_IPMSTSCD_Data_specs_1 = {
	sizeof(struct IPMSTSCD_Data),
	offsetof(struct IPMSTSCD_Data, _asn_ctx),
	asn_MAP_IPMSTSCD_Data_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_IPMSTSCD_Data = {
	"IPMSTSCD-Data",
	"IPMSTSCD-Data",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_IPMSTSCD_Data_tags_1,
	sizeof(asn_DEF_IPMSTSCD_Data_tags_1)
		/sizeof(asn_DEF_IPMSTSCD_Data_tags_1[0]), /* 1 */
	asn_DEF_IPMSTSCD_Data_tags_1,	/* Same as above */
	sizeof(asn_DEF_IPMSTSCD_Data_tags_1)
		/sizeof(asn_DEF_IPMSTSCD_Data_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_IPMSTSCD_Data_1,
	3,	/* Elements count */
	&asn_SPC_IPMSTSCD_Data_specs_1	/* Additional specs */
};

