/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "ISO10711.asn"
 */

#ifndef	_IPMSTSCD_Data_H_
#define	_IPMSTSCD_Data_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <NativeEnumerated.h>
#include "IpmstscdLoopTypeDetectorInformation.h"
#include "IpmstscdImageTypeDetectorInformation.h"
#include "IpmstscdIDTypeDetectorInformation.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ipmstscdDetType {
	ipmstscdDetType_loopTypeDetector	= 0,
	ipmstscdDetType_imageTypeDetector	= 1,
	ipmstscdDetType_idBaseTypeDetector	= 2
} e_ipmstscdDetType;
typedef enum ipmstscdDetInformation_PR {
	ipmstscdDetInformation_PR_NOTHING,	/* No components present */
	ipmstscdDetInformation_PR_loopTypeDetInf,
	ipmstscdDetInformation_PR_imageTypeDetInf,
	ipmstscdDetInformation_PR_idTypeDetInfo
} ipmstscdDetInformation_PR;

/* Forward declarations */
struct GeneralTimeLocationCore;

/* IPMSTSCD-Data */
typedef struct IPMSTSCD_Data {
	long	 detectorController_index;
	struct GeneralTimeLocationCore	*detectorController_Time_Location	/* OPTIONAL */;
	struct ipmstscdDetData {
		A_SEQUENCE_OF(struct Member {
			long	 ipmstscdDetID;
			long	 ipmstscdDetType;
			struct ipmstscdDetInformation {
				ipmstscdDetInformation_PR present;
				union ipmstscdDetInformation_u {
					IpmstscdLoopTypeDetectorInformation_t	 loopTypeDetInf;
					IpmstscdImageTypeDetectorInformation_t	 imageTypeDetInf;
					IpmstscdIDTypeDetectorInformation_t	 idTypeDetInfo;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} ipmstscdDetInformation;
			struct GeneralTimeLocationCore	*detector_time_location	/* OPTIONAL */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ipmstscdDetData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IPMSTSCD_Data_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ipmstscdDetType_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IPMSTSCD_Data;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GeneralTimeLocationCore.h"

#endif	/* _IPMSTSCD_Data_H_ */
#include <asn_internal.h>
