/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../DataPacketStructuresV3MarkRetallack.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IpmstscdImageTypeDetectorInformationType2_H_
#define	_IpmstscdImageTypeDetectorInformationType2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DirectionDensitySeq;

/* IpmstscdImageTypeDetectorInformationType2 */
typedef struct IpmstscdImageTypeDetectorInformationType2 {
	struct IpmstscdImageTypeDetectorInformationType2__congestionInfo {
		long	 congestionLength1;
		long	 vehicleStartPosition1;
		long	 congestionLength2;
		long	 vehicleStartPosition2;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} congestionInfo;
	struct IpmstscdImageTypeDetectorInformationType2__directionDensity {
		A_SEQUENCE_OF(struct DirectionDensitySeq) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} directionDensity;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpmstscdImageTypeDetectorInformationType2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IpmstscdImageTypeDetectorInformationType2;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DirectionDensitySeq.h"

#endif	/* _IpmstscdImageTypeDetectorInformationType2_H_ */
#include <asn_internal.h>
