/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IpmstscdLoopTypeDetectorInformation-Type2-Message"
 * 	found in "../ISO10711.asn"
 */

#ifndef	_IpmstscdLoopTypeDetectorInformation_H_
#define	_IpmstscdLoopTypeDetectorInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <NativeReal.h>
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum loopErrorState {
	loopErrorState_openLoopCircuit	= 1,
	loopErrorState_shortLoopCircuit	= 2,
	loopErrorState_occupancyError	= 3,
	loopErrorState_nonoccupancyError	= 4,
	loopErrorState_volumeError	= 5,
	loopErrorState_parameterInvalid	= 6,
	loopErrorState_managementNeeded	= 7
} e_loopErrorState;

/* Forward declarations */
struct IpmstscdOccNoccHistory;

/* IpmstscdLoopTypeDetectorInformation */
typedef struct IpmstscdLoopTypeDetectorInformation {
	long	*loopDataDuration	/* OPTIONAL */;
	BOOLEAN_t	 loopOccupancyState;
	long	 loopOccupancyStateDuration;
	long	 loopOccupancyPreviousStateDuration;
	double	 loopOccupancyRate;
	double	*loopSpeed	/* OPTIONAL */;
	long	 loopVolume;
	struct loopOccNoccHistory {
		A_SEQUENCE_OF(struct IpmstscdOccNoccHistory) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *loopOccNoccHistory;
	long	*loopErrorState	/* OPTIONAL */;
	OCTET_STRING_t	*loopUserData	/* OPTIONAL */;
	long	*loopTargetType	/* OPTIONAL */;
	BOOLEAN_t	*loopDirectionDiscrimination	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpmstscdLoopTypeDetectorInformation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_loopErrorState_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IpmstscdLoopTypeDetectorInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IpmstscdOccNoccHistory.h"

#endif	/* _IpmstscdLoopTypeDetectorInformation_H_ */
#include <asn_internal.h>
