/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../Annex_A_10711_v2.0.asn"
 * 	`asn1c -fcompound-names`
 */

#include "IpmstscdOccTypeDetectorInformationType2.h"

static int
memb_det_Accmulated_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 48)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_det_SerialInfo_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 48)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_det_Velocity_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size <= 160)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_det_Info_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 6)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_iDetStatus_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_det_Accmulated_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Det_AccmulatedSeq,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_det_Accmulated_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_det_Accmulated_specs_2 = {
	sizeof(struct IpmstscdOccTypeDetectorInformationType2__det_Accmulated),
	offsetof(struct IpmstscdOccTypeDetectorInformationType2__det_Accmulated, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_det_Accmulated_2 = {
	"det-Accmulated",
	"det-Accmulated",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_det_Accmulated_tags_2,
	sizeof(asn_DEF_det_Accmulated_tags_2)
		/sizeof(asn_DEF_det_Accmulated_tags_2[0]) - 1, /* 1 */
	asn_DEF_det_Accmulated_tags_2,	/* Same as above */
	sizeof(asn_DEF_det_Accmulated_tags_2)
		/sizeof(asn_DEF_det_Accmulated_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_det_Accmulated_2,
	1,	/* Single element */
	&asn_SPC_det_Accmulated_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_det_SerialInfo_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Det_SerialInfoSeq,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_det_SerialInfo_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_det_SerialInfo_specs_4 = {
	sizeof(struct IpmstscdOccTypeDetectorInformationType2__det_SerialInfo),
	offsetof(struct IpmstscdOccTypeDetectorInformationType2__det_SerialInfo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_det_SerialInfo_4 = {
	"det-SerialInfo",
	"det-SerialInfo",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_det_SerialInfo_tags_4,
	sizeof(asn_DEF_det_SerialInfo_tags_4)
		/sizeof(asn_DEF_det_SerialInfo_tags_4[0]) - 1, /* 1 */
	asn_DEF_det_SerialInfo_tags_4,	/* Same as above */
	sizeof(asn_DEF_det_SerialInfo_tags_4)
		/sizeof(asn_DEF_det_SerialInfo_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_det_SerialInfo_4,
	1,	/* Single element */
	&asn_SPC_det_SerialInfo_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_det_Velocity_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Det_VelocitySeq,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_det_Velocity_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_det_Velocity_specs_6 = {
	sizeof(struct IpmstscdOccTypeDetectorInformationType2__det_Velocity),
	offsetof(struct IpmstscdOccTypeDetectorInformationType2__det_Velocity, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_det_Velocity_6 = {
	"det-Velocity",
	"det-Velocity",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_det_Velocity_tags_6,
	sizeof(asn_DEF_det_Velocity_tags_6)
		/sizeof(asn_DEF_det_Velocity_tags_6[0]) - 1, /* 1 */
	asn_DEF_det_Velocity_tags_6,	/* Same as above */
	sizeof(asn_DEF_det_Velocity_tags_6)
		/sizeof(asn_DEF_det_Velocity_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_det_Velocity_6,
	1,	/* Single element */
	&asn_SPC_det_Velocity_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_IpmstscdOccTypeDetectorInformationType2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IpmstscdOccTypeDetectorInformationType2, det_Accmulated),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_det_Accmulated_2,
		memb_det_Accmulated_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"det-Accmulated"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpmstscdOccTypeDetectorInformationType2, det_SerialInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_det_SerialInfo_4,
		memb_det_SerialInfo_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"det-SerialInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpmstscdOccTypeDetectorInformationType2, det_Velocity),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_det_Velocity_6,
		memb_det_Velocity_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"det-Velocity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpmstscdOccTypeDetectorInformationType2, det_Info),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_det_Info_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"det-Info"
		},
	{ ATF_POINTER, 1, offsetof(struct IpmstscdOccTypeDetectorInformationType2, iDetStatus),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		memb_iDetStatus_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iDetStatus"
		},
};
static const ber_tlv_tag_t asn_DEF_IpmstscdOccTypeDetectorInformationType2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IpmstscdOccTypeDetectorInformationType2_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* det-Accmulated */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* det-SerialInfo */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* det-Velocity */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* det-Info */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iDetStatus */
};
static asn_SEQUENCE_specifics_t asn_SPC_IpmstscdOccTypeDetectorInformationType2_specs_1 = {
	sizeof(struct IpmstscdOccTypeDetectorInformationType2),
	offsetof(struct IpmstscdOccTypeDetectorInformationType2, _asn_ctx),
	asn_MAP_IpmstscdOccTypeDetectorInformationType2_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_IpmstscdOccTypeDetectorInformationType2 = {
	"IpmstscdOccTypeDetectorInformationType2",
	"IpmstscdOccTypeDetectorInformationType2",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_IpmstscdOccTypeDetectorInformationType2_tags_1,
	sizeof(asn_DEF_IpmstscdOccTypeDetectorInformationType2_tags_1)
		/sizeof(asn_DEF_IpmstscdOccTypeDetectorInformationType2_tags_1[0]), /* 1 */
	asn_DEF_IpmstscdOccTypeDetectorInformationType2_tags_1,	/* Same as above */
	sizeof(asn_DEF_IpmstscdOccTypeDetectorInformationType2_tags_1)
		/sizeof(asn_DEF_IpmstscdOccTypeDetectorInformationType2_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_IpmstscdOccTypeDetectorInformationType2_1,
	5,	/* Elements count */
	&asn_SPC_IpmstscdOccTypeDetectorInformationType2_specs_1	/* Additional specs */
};

