/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../DataPacketStructuresV3MarkRetallack.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_IpmstscdImageTypeDetectorInformation_H_
#define	_IpmstscdImageTypeDetectorInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeReal.h>
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IpmstscdImageTypeDetectorInformation__errorState {
	IpmstscdImageTypeDetectorInformation__errorState_deviceFail	= 1,
	IpmstscdImageTypeDetectorInformation__errorState_unstableUtility	= 2,
	IpmstscdImageTypeDetectorInformation__errorState_connectionFail	= 3,
	IpmstscdImageTypeDetectorInformation__errorState_imageProcessingFail	= 4,
	IpmstscdImageTypeDetectorInformation__errorState_parameterInvalid	= 5,
	IpmstscdImageTypeDetectorInformation__errorState_volumeError	= 6,
	IpmstscdImageTypeDetectorInformation__errorState_managementNeeded	= 7
	/*
	 * Enumeration is extensible
	 */
} e_IpmstscdImageTypeDetectorInformation__errorState;

/* Forward declarations */
struct IpmstscdOccNoccHistory;

/* IpmstscdImageTypeDetectorInformation */
typedef struct IpmstscdImageTypeDetectorInformation {
	long	*dataDuration	/* OPTIONAL */;
	long	 volumeQuantity;
	long	*queueLength	/* OPTIONAL */;
	double	*averageOccupancyRate	/* OPTIONAL */;
	double	*averageSpeed	/* OPTIONAL */;
	struct IpmstscdOccNoccHistory	*occNoccHistory	/* OPTIONAL */;
	long	*errorState	/* OPTIONAL */;
	OCTET_STRING_t	*userData	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpmstscdImageTypeDetectorInformation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_errorState_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IpmstscdImageTypeDetectorInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IpmstscdOccNoccHistory.h"

#endif	/* _IpmstscdImageTypeDetectorInformation_H_ */
#include <asn_internal.h>
