/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "ISO14927-1.asn"
 */

#ifndef	_Time_H_
#define	_Time_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum time_SecondFractions_PR {
	time_SecondFractions_PR_NOTHING,	/* No components present */
	time_SecondFractions_PR_deci_seconds,
	time_SecondFractions_PR_centi_seconds,
	time_SecondFractions_PR_milliseconds,
	/* Extensions may appear below */
	
} time_SecondFractions_PR;

/* Time */
typedef struct Time {
	long	*time_Year_qty	/* OPTIONAL */;
	long	*time_Month_qty	/* OPTIONAL */;
	long	*time_Day_qty	/* OPTIONAL */;
	long	 time_Hour_qty	/* DEFAULT 0 */;
	long	 time_Minute_qty	/* DEFAULT 0 */;
	long	 time_Second_qty	/* DEFAULT 0 */;
	struct time_SecondFractions {
		time_SecondFractions_PR present;
		union Time__time_SecondFractions_u {
			long	 deci_seconds;
			long	 centi_seconds;
			long	 milliseconds;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} time_SecondFractions;
	struct time_Timezone {
		long	 timezone_Hour_qty	/* DEFAULT 0 */;
		long	 time_Minute_qty	/* DEFAULT 0 */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} time_Timezone;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Time_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Time;

#ifdef __cplusplus
}
#endif

#endif	/* _Time_H_ */
#include <asn_internal.h>
