/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ISO14827-2"
 * 	found in "../ISO14927-1.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_Time_H_
#define	_Time_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Time__secondFractions_PR {
	Time__secondFractions_PR_NOTHING,	/* No components present */
	Time__secondFractions_PR_time_Deciseconds_qty,
	Time__secondFractions_PR_time_Centiseconds_qty,
	Time__secondFractions_PR_time_Milliseconds_qty,
	/* Extensions may appear below */
	
} Time__secondFractions_PR;

/* Time */
typedef struct Time {
	long	*time_Year_qty	/* OPTIONAL */;
	long	*time_Month_qty	/* OPTIONAL */;
	long	*time_Day_qty	/* OPTIONAL */;
	long	 time_Hour_qty	/* DEFAULT 0 */;
	long	 time_Minute_qty	/* DEFAULT 0 */;
	long	 time_Second_qty	/* DEFAULT 0 */;
	struct Time__secondFractions {
		Time__secondFractions_PR present;
		union Time__secondFractions_u {
			long	 time_Deciseconds_qty;
			long	 time_Centiseconds_qty;
			long	 time_Milliseconds_qty;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *secondFractions;
	struct Time__timezone {
		long	 time_TimeZoneHour_qty	/* DEFAULT 0 */;
		long	 time_TimeZoneMinute_qty	/* DEFAULT 0 */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *timezone;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Time_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Time;

#ifdef __cplusplus
}
#endif

#endif	/* _Time_H_ */
#include <asn_internal.h>
