/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IPMTSCD"
 * 	found in "../Annex_A_10711_v2.0.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VehicleInfoSeq_H_
#define	_VehicleInfoSeq_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleInfoSeq */
typedef struct VehicleInfoSeq {
	OCTET_STRING_t	 vehicleID;
	OCTET_STRING_t	*idData	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleInfoSeq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleInfoSeq;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleInfoSeq_H_ */
#include <asn_internal.h>
