/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "IpmstscdIDTypeDetectorInformation-Type2-Message"
 * 	found in "../ISO10711.asn"
 */

#ifndef	_VehicleInfo_H_
#define	_VehicleInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleInfo */
typedef struct VehicleInfo {
	A_SEQUENCE_OF(struct Member {
		OCTET_STRING_t	 vehicleID;
		OCTET_STRING_t	*idData	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleInfo_H_ */
#include <asn_internal.h>
